<section class="contenedorMain">
        <div class="contactos">
            <h2>Contactos</h2>
            <table>
                <thead>
                    <tr>
                        <td>Country</td>
                        <td>Phone number</td>
                        <td>E-mail</td>
                    </tr>
                </thead>
                <tr>
                    <td>Argentine</td>
                    <td>+54 2494 78654</td>
                    <td><a href="">arg.rentcar@luxor.com</a></td>
                </tr>
                <tr>
                    <td>EEUU</td>
                    <td>+1 8764 78654</td>
                    <td><a href="">eeuu.rentcar@luxor.com</a></td>
                </tr>
                <tr>
                    <td>Italy</td>
                    <td>+39 794 4378654</td>
                    <td><a href="">it.rentcar@luxor.com</a></td>
                </tr>
                <tr>
                    <td>Spain</td>
                    <td>+32 494 178654</td>
                    <td><a href="">es.rentcar@luxor.com</a></td>
                </tr>
            </table>
        </div>
    </section>