<section class="contenedorMain">
    <h2>Detalle Reserva</h2>
    <div class="catalogo">
        <ul>
            <li><b>ID:</b> <?php echo $reserva->id ?> </li>
            <li><b>Fecha de reserva:</b> <?php echo $reserva->fecha_reserva ?></li>
            <li><b>Cantidad de dias:</b> <?php echo $reserva->cant_dias ?></li>
            <li><b>ID del vehiculo:</b> <?php echo $reserva->id_vehiculo ?></li>
        </ul>
    </div>
    <?php if ($usuario) { ?>
            <div>
            <button onclick="location.href='showFormActualizarReserva/<?php echo $reserva->id ?>'" >Actualizar</a>
            </div>
            <br>
            <div>
            <button onclick="location.href='eliminarReserva/<?php echo $reserva->id ?>'" >Eliminar</a>
            </div>
        <?php } ?>
</section>