<section class="contenedorMain">
    <h2>Detalles</h2>
    <div class="catalogo">
        <ul>
            <img src="<?php echo $vehiculo->imagen ?>" alt="" class="img-auto">
            <li><b>Marca:</b> <?php echo $vehiculo->marca ?> </li>
            <li><b>Modelo:</b> <?php echo $vehiculo->modelo ?></li>
            <li><b>Matricula:</b> <?php echo $vehiculo->matricula ?></li>
            <li><b>Precio por dia:</b> $<?php echo $vehiculo->precio_dia ?></li>
        </ul>
        <?php if ($usuario) { ?>
            <a href="showFormActualizarVehiculo/<?php echo "$vehiculo->id" ?>">Actualizar</a>
            <a href="eliminar/<?php echo "$vehiculo->id" ?>">Eliminar</a>
        <?php } ?>
    </div>
</section>