<section class="contenedorMain">
    <h2>Formulario de alta Vehiculos</h2>
    <form action="insertar" method="post">
        <div>
            <label>Marca: <input type="text" name="marca" required></label>
        </div>
        <br>
        <div>
        <label>Modelo: </label><select name="modelo">
                <option value="2019">2019</option>
                <option value="2020">2020</option>
                <option value="2021">2021</option>
                <option value="2022">2022</option>
                <option value="2023">2023</option>
            </select>
        </div>
        <br>
        <div>
            <label>Matricula: <input type="text" name="matricula" required></label>
        </div>
        <br>
        <div>
            <label>Precio dia: <input type="text" name="precio" required></label>
        </div>
        <br>
        <div>
            <label>Imagen (url): <input type="text" name="imagen" required></label>
        </div>
        <br>
        <div>
            <button type="submit">Agregar</button>
        </div>
    </form>
</section>