<section class="contenedorMain">
    <h2>Formulario de actualizacion de Vehiculos</h2>
    <img src="<?php echo $vehiculo->imagen ?>" alt="" class="img-auto">

    <form action="actualizarVehiculo/<?php echo "$vehiculo->id" ?>" method="post">
        <div>
            <label>Marca: <input type="text" name="marca" value="<?php echo $vehiculo->marca ?>" required></label>
        </div>
        <br>
        <div>
            <label>Modelo: </label>
            <select name="modelo">
                <?php for ($i = 2019; $i < 2024; $i++) {
                    if ($vehiculo->modelo == $i) { ?>
                        <option value="<?php echo "$i" ?>" selected> <?php echo "$i" ?> </option>
                    <?php } else { ?>
                        <option value="<?php echo "$i" ?>"> <?php echo "$i" ?> </option>
                <?php }
                } ?>
            </select>
        </div>
        <br>
        <div>
            <label>Matricula: <input type="text" name="matricula" value="<?php echo $vehiculo->matricula ?>" required></label>
        </div>
        <br>
        <div>
            <label>Precio dia: <input type="text" name="precio" value="<?php echo $vehiculo->precio_dia ?>" required></label>
        </div>
        <br>
        <div>
            <label>Imagen (url): <input type="text" name="imagen" value="<?php echo $vehiculo->imagen ?>" required></label>
        </div>
        <br>
        <div>
            <button type="submit">Actualizar</button>
        </div>
    </form>
</section>