<section class="contenedorMain">
    <h2>Formulario de alta Vehiculos</h2>
    <form action="insertar" method="post">
        <div>
            <label>Marca: <input type="text" name="marca" required></label>
        </div>
        <div>
            <label>Modelo: <input type="text" name="modelo" required></label>
        </div>
        <div>
            <label>Matricula: <input type="text" name="matricula" required></label>
        </div>
        <div>
            <label>Precio dia: <input type="text" name="precio" required></label>
        </div>
        <div>
            <label>Imagen (url): <input type="text" name="imagen" required></label>
        </div>
        <div>
            <button type="submit">Agregar</button>
        </div>
    </form>
</section>