<section class="contenedorMain">
    <h2>Formulario de actualizacion de Reservas</h2>

    <form action="actualizarReserva/<?php echo "$reserva->id" ?>" method="post">
        <div>
            <label>ID: <?php echo $reserva->id ?></label>
        </div>
        <br>
        <div>
            <label>Fecha de reserva: <input type="date" name="fecha" value="<?php echo $reserva->fecha_reserva ?>" ></label>
        </div>
        <br>
        <div>
            <div>
                <label>Cantidad de dias: <input type="number" step="1" name="cantDias" value="<?php echo $reserva->cant_dias ?>" ></label>
            </div>
            <br>
            <label>Vehiculo: </label>
            <select name="select-reserva">
                <?php foreach ($vehiculos as $vehiculo) {
                    if ($reserva->id_vehiculo == $vehiculo->id) { ?>
                        <option value="<?php echo $vehiculo->id ?>" selected> <?php echo "$vehiculo->marca / $vehiculo->matricula" ?></option>
                    <?php } else { ?>
                        <option value="<?php echo $vehiculo->id ?>"> <?php echo "$vehiculo->marca / $vehiculo->matricula" ?></option>
                <?php }
                } ?>
            </select>
        </div>
        <br><br>
        <div>
            <button type="submit">Actualizar</button>
        </div>
    </form>
</section>