<section class="contenedorMain">
    <form id="formSignIn" method="post" action="login">
        <h2>Sign-In</h2>
        <div>
            <label for="" id="labelEmail">E-mail:</label> <input type="email" name="email" required>
        </div>
        <div>
            <label for="" id="labelPassword">Password:</label> <input type="password" name="password" minlength="5" maxlength="10" required>
        </div>
        <div>
            <label for="">Si todavia no estas registrado, haz <a href="">click aqui</a></label>
        </div>
        <div>
            <button type="submit" class="btn-signIn">Enviar</button>
        </div>
    </form>
</section>