<section class="contenedorMain">
    <h2>Reservas del vehiculo con id <?php echo $vehiculo->id ?></h2>
    <div class="catalogo">
        <ul>
            <img src="<?php echo $vehiculo->imagen ?>" alt="" class="img-auto">
            <li><b>Marca:</b> <?php echo $vehiculo->marca ?> </li>
            <li><b>Modelo:</b> <?php echo $vehiculo->modelo ?></li>
            <li><b>Matricula:</b> <?php echo $vehiculo->matricula ?></li>
            <li><b>Precio por dia:</b> $<?php echo $vehiculo->precio_dia ?></li>
            <li><b>Estado:</b> <?php if ($vehiculo->reservado)
                                    echo 'Reservado';
                                else
                                    echo 'Disponible'; ?>
            </li>
        </ul>
        <div class="contactos">
            <table>
                <thead>
                    <tr>
                        <td>Fecha Reserva</td>
                        <td>Cantidad de dias</td>
                        <td>Total a Pagar</td>
                        <td>ID reserva</td>
                    </tr>
                </thead>
                <?php foreach ($reservas as $reserva) { ?>
                    <tr>
                        <td><?php echo $reserva->fecha_reserva ?></td>
                        <td><?php echo $reserva->cant_dias ?></td>
                        <td>$<?php echo $reserva->cant_dias * $vehiculo->precio_dia ?></td>
                        <td><?php echo $reserva->id ?></td>
                    </tr>
                <?php } ?>


            </table>
        </div>
    </div>
</section>