<section class="contenedorMain">
        <h2>Servicios</h2>
        <ul>
            <li><strong>Alquiler de vehículos de lujo:</strong> Ofrecemos una amplia gama de vehículos de lujo para alquilar, desde sedanes y SUVs hasta deportivos y convertibles.</li>
            <br>
            <li><strong>Servicio de entrega y recogida:</strong> Proporcionamos la comodidad de entregar y recoger el vehículo alquilado en la ubicación preferida del cliente.</li>
            <br>
            <li><strong>Reservas en línea:</strong> Permitimos a los clientes reservar y pagar su vehículo de alquiler a través de la página web.</li>
            <br>
            <li><strong>Asistencia en carretera 24/7:</strong> Aseguramos a los clientes que recibirán asistencia en caso de cualquier problema con el vehículo.</li>
            <br>
            <li><strong>Opciones de seguro:</strong> Ofrecemos diferentes opciones de seguro para proteger a los clientes durante el período de alquiler.</li>
            <br>
            <li><strong>Alquiler a largo plazo:</strong> Proporcionamos opciones de alquiler a largo plazo para clientes que necesiten un vehículo de lujo durante un período prolongado.</li>
            <br>
            <li><strong>Vehículos con conductor:</strong> Ofrecemos la opción de alquilar un vehículo con un conductor profesional.</li>
            <br>
            <li><strong>Paquetes personalizados:</strong> Permitimos a los clientes personalizar su experiencia de alquiler según sus necesidades específicas.</li>
        </ul>
    </section>